### ISSUE TITLE
Add Support for Encrypted Word Document

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#139]
Currently, Bookworm can open an encrypted .pdf file and asks for a password when opening such a file, but there is no support for encrypted Word documents. When opening such a document, Bookworm gives an error.

## Describe the solution you'd like
Add the ability to view encrypted Word files in Bookworm.

## Additional context

Here is the <details><summary>log</summary>
<p>
ERROR - bookworm.bookworm.gui.book_viewer - 23/03/2022 17:51:26 - bookworm_threaded_worker_0 (3432):
Unsupported file format

concurrent.futures.process._RemoteTraceback: 
"""

Traceback (most recent call last):

  File "concurrent\futures\process.py", line 243, in _process_worker

  File "bookworm\document\formats\word.py", line 59, in get_converted_filename

  File "mammoth\__init__.py", line 12, in convert_to_html

  File "mammoth\__init__.py", line 26, in convert

  File "mammoth\results.py", line 15, in bind

  File "mammoth\__init__.py", line 27, in <lambda>

  File "mammoth\docx\__init__.py", line 23, in read

  File "mammoth\zips.py", line 9, in open_zip

  File "zipfile.py", line 1257, in __init__

  File "zipfile.py", line 1324, in _RealGetContents

zipfile.BadZipFile: File is not a zip file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "bookworm\reader.py", line 81, in read_document

  File "bookworm\document\formats\word.py", line 43, in read

  File "concurrent\futures\_base.py", line 446, in result

  File "concurrent\futures\_base.py", line 391, in __get_result

zipfile.BadZipFile: File is not a zip file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "bookworm\gui\book_viewer\__init__.py", line 102, in resolve_document

  File "bookworm\reader.py", line 90, in read_document

bookworm.reader.ReaderError: Failed to open document
</p>
</details>

Here is a test document that you can view in Bookworm, password 123 if needed.
[testing.docx](https://github.com/blindpandas/bookworm/files/8333585/testing.docx)

**Comment by mush42** [comment]
@DraganRatkovich 
I will look into this issue.

**Comment by mush42** [comment]
Note to my future self. Here is a mature package to handle this one:
https://github.com/nolze/msoffcrypto-tool

**Comment by DraganRatkovich** [comment]
Hello @mush42

Works very well, thank you.
