### ISSUE TITLE
The latest appveyor build doesn't work

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#233]
## Describe the Problem
The latest appveyor build doesn't work.
## To Reproduce

1. Install the build by the latest commit
2. Try running Bookworm or Bookshelf
3. See error:
```log
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 58, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 42, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ImportError: DLL load failed while importing win32api: 找不到指定的程序。
```

## Expected behavior
works as expected
## If the problem is related to a file, indicate the file you have opened
None
## Desktop (please complete the following information):

 - OS: [Windows 10 22H2 (AMD64) build 19045.3324]
 - Bookworm version [Latest committed build]
 - Recent settings you may have changed in Bookworm [None]

**Comment by cary-rowen** [comment]
Hi @pauliyobo
Can you take a look at this issue?
Thanks

**Comment by pauliyobo** [comment]
@cary-rowen The latest portable works and the latest installer doesn't?

**Comment by cary-rowen** [comment]
This issue occurs when a user builds a version with the latest commit overwriting a previously installed version.

**Comment by cary-rowen** [comment]
@pauliyobo 
Sorry for close it by mistake, actually this should probably be fixed as well.
Because the new version of the installation script did not clear the residual files of the previous version.

**Comment by DraganRatkovich** [comment]
Hello,

Is there anything new on this issue?

@pauliyobo As I can see from your commits in the draft pull request, you are changing AppVeyor builds with GH Actions. Will this also solve this issue?

**Comment by pauliyobo** [comment]
@cary-rowen I'm confused. Is your problem solved or not?
@DraganRatkovich not really.

**Comment by cary-rowen** [comment]
@pauliyobo 
This issue occurs when a user builds a version with the latest commit overwriting a previously installed version.
This is because the directory of the installed version will not be completely cleared when the new version installer is executed, and individual files of the old version still exist after the new version is installed.
So the portable version will not be involved in this problem.
Hope I have explained clearly.

**Comment by mush42** [comment]
@cary-rowen  @DraganRatkovich  I faced the same issue during development, but I removed the build directory manually and everything worked as expected.

Didn't think it may occur with the installed copy!

I'll take a look

Best
