### ISSUE TITLE
eunable to launch Bookworm Portable 0.2A4

### ISSUE THREAD

**Issue by a-singer** [blindpandas/bookworm#53]
## Describe the Problem

Hello,

When I unzip the file
Bookworm-0.2a4-portable.zip
and press enter on bookworm.exe, I get the following error written to the log

19/01/2021 00:08:19 root CRITICAL: Error details:
Traceback (most recent call last):
  File "bookworm\bookworm.py", line 27, in main
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\projects\bookworm-o7wa1\.venv32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "bookworm\bootstrap.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\projects\bookworm-o7wa1\.venv32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "bookworm\paths.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\projects\bookworm-o7wa1\.venv32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "bookworm\runtime.py", line 59, in <module>
  File "bookworm\runtime.py", line 48, in is_running_portable
  File "pathlib.py", line 1027, in __new__
  File "pathlib.py", line 674, in _from_parts
  File "pathlib.py", line 658, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not NoneType

## To Reproduce

1. Unzip the portable .zip file.
2. Press enter on the bookworm.exe file.
3. See error

## Expected behavior

Bookworm should launch.

## The File You've Opened

I am unable to open a file.

## Desktop (please complete the following information):

 - OS: Windows 7 SP1 64 Bit
 - Bookworm version 0.2B4
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]

**Comment by mush42** [comment]
Hi,

Thanks for reporting this bug.
The bug has been identified and fixed.
