### ISSUE TITLE
Error while checking for updates

### ISSUE THREAD

**Issue by ashleygrobler04** [blindpandas/bookworm#62]
## Describe the Problem

A clear and concise description of what the problem is.

## To Reproduce

3. See error

## The File You've Opened

Tell us what is the format of the file you've opened [e.g. PDF]. If possible, attach the file you have open in Bookworm when the problem happened.

## Desktop (please complete the following information):

 - OS: [e.g. Windows 10 64-bit]
 - Bookworm version [e.g. 0.1.0b1]
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]

## Additional context

Hi there. Since i used bookworm, i could never manage to check for updates with in the app.
When i go to the help menu, and click on "check for updates", it gives me the following error:
[Window Title]
Error Checking For Updates

[Content]
We have faced a technical problem while checking for updates. Please try again later.

[OK]
If i need to post any logs, please tell me where to find those and i will gladly do so.
I also restarted bookworm in debug mode, it still didn't fix any thing.
lastly, i found out where the logs are stored, and they all seem to be empty.
Best regards

**Comment by ashleygrobler04** [comment]
Sorry for the double comment, but i found out where the actual logs are stored this time... here are the contents of the log:
21/05/2021 08:49:36 root CRITICAL: Error details:
Traceback (most recent call last):
  File "sqlalchemy\engine\base.py", line 1276, in _execute_context
  File "sqlalchemy\engine\default.py", line 609, in do_execute
sqlite3.OperationalError: table book already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\bookworm.py", line 20, in main
  File "bookworm\bootstrap.py", line 133, in run
  File "bookworm\bootstrap.py", line 93, in init_app_and_run_main_loop
  File "bookworm\bootstrap.py", line 62, in setupSubsystems
  File "bookworm\database\__init__.py", line 26, in init_database
  File "db_magic\magic.py", line 232, in setup_database
  File "sqlalchemy\sql\schema.py", line 4553, in create_all
  File "sqlalchemy\engine\base.py", line 2095, in _run_visitor
  File "sqlalchemy\engine\base.py", line 1656, in _run_visitor
  File "sqlalchemy\sql\visitors.py", line 145, in traverse_single
  File "sqlalchemy\sql\ddl.py", line 783, in visit_metadata
  File "sqlalchemy\sql\visitors.py", line 145, in traverse_single
  File "sqlalchemy\sql\ddl.py", line 827, in visit_table
  File "sqlalchemy\engine\base.py", line 1011, in execute
  File "sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
  File "sqlalchemy\engine\base.py", line 1068, in _execute_ddl
  File "sqlalchemy\engine\base.py", line 1316, in _execute_context
  File "sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
  File "sqlalchemy\util\compat.py", line 182, in raise_
  File "sqlalchemy\engine\base.py", line 1276, in _execute_context
  File "sqlalchemy\engine\default.py", line 609, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table book already exists
[SQL: 
CREATE TABLE book (
	id INTEGER NOT NULL, 
	title VARCHAR(512) NOT NULL, 
	uri VARCHAR(1024) NOT NULL, 
	PRIMARY KEY (id)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by mohdshara** [comment]
Hi.

Just to confirm that I get the exact same error when checking for updates.

**Comment by ashleygrobler04** [comment]
I hope this error can get fixed as soon as possible.

**Comment by mush42** [comment]
It will be fixed automagically when we release the next beta.
