### ISSUE TITLE
Get error when opening Mobi Files

### ISSUE THREAD

**Issue by stefmagura** [blindpandas/bookworm#79]
## Describe the Problem:

When I try to open Mobi Files, I get an error message saying that the files has either been corrupted or damaged.  This is true whether I convert from another document, or download a Mobi File off the internet.  This is what it showed when I started Bookworm in debug mode.

Traceback (most recent call last):
  File "bookworm\reader.py", line 77, in read_document
  File "bookworm\document_formats\mobi_document.py", line 56, in read
bookworm.document_formats.base.exceptions.ChangeDocument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ebooklib\utils.py", line 35, in parse_string
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bookworm\reader.py", line 77, in read_document
  File "bookworm\document_formats\epub_document.py", line 149, in read
  File "ebooklib\epub.py", line 1739, in read_epub
  File "ebooklib\epub.py", line 1397, in load
  File "ebooklib\epub.py", line 1694, in _load
  File "ebooklib\epub.py", line 1665, in _load_opf_file
  File "ebooklib\epub.py", line 1648, in _load_spine
  File "ebooklib\epub.py", line 1547, in _parse_ncx
  File "ebooklib\utils.py", line 37, in parse_string
  File "src\lxml\etree.pyx", line 3521, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 11
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 11, column 37

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\menubar.py", line 199, in onOpenEBook
  File "bookworm\gui\book_viewer\__init__.py", line 342, in open_uri
  File "bookworm\gui\book_viewer\__init__.py", line 68, in __init__
  File "bookworm\gui\book_viewer\__init__.py", line 84, in init_resolver
  File "bookworm\gui\book_viewer\__init__.py", line 157, in resolve_document
  File "bookworm\gui\book_viewer\__init__.py", line 99, in resolve_document
  File "bookworm\reader.py", line 84, in read_document
  File "bookworm\reader.py", line 86, in read_document
bookworm.reader.ReaderError: Failed to open document

A clear and concise description of what the problem is.

## To Reproduce

3. See error

## The File You've Opened

Tell us what is the format of the file you've opened [e.g. PDF]. If possible, attach the file you have open in Bookworm when the problem happened.

## Desktop (please complete the following information):

 - OS: [e.g. Windows 10 64-bit]
 - Bookworm version [e.g. 0.1.0b1]
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]

**Comment by mush42** [comment]
MOBI support is working (based on our tests). Unless you provide us with a specific example file, we'll not be able to reproduce this issue. Don't hesitate to re-open if you have more info.

Regards,
