### ISSUE TITLE
Bookworm cannot open a pdf file which I can access with microsoft edge fine

### ISSUE THREAD

**Issue by burakyuksek** [blindpandas/bookworm#82]
## Describe the Problem
It does not open a pdf file which can be accessed fine by mircosoft edge.
A clear and concise description of what the problem is.
It fails to open the file and says that it may be corrupted, which is not true. The following is logged in debug:
--- Logging error ---
Traceback (most recent call last):
  File "bookworm\reader.py", line 77, in read_document
  File "bookworm\document_formats\pdf_document.py", line 82, in read
  File "bookworm\document_formats\pdf_document.py", line 77, in create_xpdf_document
  File "src/pyxpdf/document.pxi", line 114, in pyxpdf.xpdf.Document.__cinit__
  File "src/pyxpdf/document.pxi", line 216, in pyxpdf.xpdf.Document.check
pyxpdf.xpdf.PDFIOError: Failed to load C:\Users\Burak\Desktop\derslerim\okul\Üniversite\4\2021 Güz Vize Sınav Takvimi.pdf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\__init__.py", line 99, in resolve_document
  File "bookworm\reader.py", line 86, in read_document
bookworm.reader.ReaderError: Failed to open document

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1082, in emit
  File "C:\Python39-x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 593: character maps to <undefined>
Call stack:
  File "launcher.py", line 4, in <module>
  File "bookworm\bookworm.py", line 20, in main
  File "bookworm\bootstrap.py", line 133, in run
  File "bookworm\bootstrap.py", line 126, in init_app_and_run_main_loop
  File "wx\core.py", line 2237, in MainLoop
  File "bookworm\gui\book_viewer\menubar.py", line 199, in onOpenEBook
  File "bookworm\gui\book_viewer\__init__.py", line 342, in open_uri
  File "bookworm\gui\book_viewer\__init__.py", line 68, in __init__
  File "bookworm\gui\book_viewer\__init__.py", line 84, in init_resolver
  File "bookworm\gui\book_viewer\__init__.py", line 126, in resolve_document
  File "logging\__init__.py", line 1469, in exception
  File "logging\__init__.py", line 1463, in error
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 948, in handle
  File "logging\handlers.py", line 75, in emit
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1087, in emit
Message: 'Unsupported file format'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "bookworm\reader.py", line 77, in read_document
  File "bookworm\document_formats\pdf_document.py", line 82, in read
  File "bookworm\document_formats\pdf_document.py", line 77, in create_xpdf_document
  File "src/pyxpdf/document.pxi", line 114, in pyxpdf.xpdf.Document.__cinit__
  File "src/pyxpdf/document.pxi", line 216, in pyxpdf.xpdf.Document.check
pyxpdf.xpdf.PDFIOError: Failed to load C:\Users\Burak\Desktop\derslerim\okul\Üniversite\4\2021 Güz Vize Sınav Takvimi.pdf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\__init__.py", line 99, in resolve_document
  File "bookworm\reader.py", line 86, in read_document
bookworm.reader.ReaderError: Failed to open document

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1082, in emit
  File "C:\Python39-x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 593: character maps to <undefined>
Call stack:
  File "launcher.py", line 4, in <module>
  File "bookworm\bookworm.py", line 20, in main
  File "bookworm\bootstrap.py", line 133, in run
  File "bookworm\bootstrap.py", line 126, in init_app_and_run_main_loop
  File "wx\core.py", line 2237, in MainLoop
  File "bookworm\gui\book_viewer\menubar.py", line 199, in onOpenEBook
  File "bookworm\gui\book_viewer\__init__.py", line 342, in open_uri
  File "bookworm\gui\book_viewer\__init__.py", line 68, in __init__
  File "bookworm\gui\book_viewer\__init__.py", line 84, in init_resolver
  File "bookworm\gui\book_viewer\__init__.py", line 126, in resolve_document
  File "logging\__init__.py", line 1469, in exception
  File "logging\__init__.py", line 1463, in error
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 948, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1087, in emit
Message: 'Unsupported file format'
Arguments: ()
Traceback (most recent call last):
  File "bookworm\reader.py", line 77, in read_document
  File "bookworm\document_formats\pdf_document.py", line 82, in read
  File "bookworm\document_formats\pdf_document.py", line 77, in create_xpdf_document
  File "src/pyxpdf/document.pxi", line 114, in pyxpdf.xpdf.Document.__cinit__
  File "src/pyxpdf/document.pxi", line 216, in pyxpdf.xpdf.Document.check
pyxpdf.xpdf.PDFIOError: Failed to load C:\Users\Burak\Desktop\derslerim\okul\Üniversite\4\2021 Güz Vize Sınav Takvimi.pdf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\menubar.py", line 199, in onOpenEBook
  File "bookworm\gui\book_viewer\__init__.py", line 342, in open_uri
  File "bookworm\gui\book_viewer\__init__.py", line 68, in __init__
  File "bookworm\gui\book_viewer\__init__.py", line 84, in init_resolver
  File "bookworm\gui\book_viewer\__init__.py", line 157, in resolve_document
  File "bookworm\gui\book_viewer\__init__.py", line 99, in resolve_document
  File "bookworm\reader.py", line 86, in read_document
bookworm.reader.ReaderError: Failed to open document

## To Reproduce
Open a pdf document which I am not sure if I can give out, because this is the list of midterm dates for university.
1. Go to 'bookworm window'
2. Click on 'file>open' and select the document
3. See error "Could not open file
.Either the file  has been damaged during download, or it has been corrupted in some other way."

## Expected behavior
The file can be successfully opened and viewed

## The File You've Opened

Tell us what is the format of the file you've opened [e.g. PDF]. If possible, attach the file you have open in Bookworm when the problem happened.
.pdf
## Desktop (please complete the following information):

 - OS: Windows 10 64-bit
 - Bookworm version 0.4b1
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]

**Comment by mush42** [comment]
Hi @burakyuksek 

This bug has been already fixed. The fix will be released as a part of the next update.

Closing this issue for now. Please don't hesitate to reopen if the issue persist after the next update.

Regards,
