### ISSUE TITLE
BookWorm doesn't open russian and uzbek books.

### ISSUE THREAD

**Issue by shaxzodxasanov** [blindpandas/bookworm#88]
##When opening file bookWorm says
Could not open file
.Either the file  has been damaged during download, or it has been corrupted in some other way.

##debug message
Traceback (most recent call last):
  File "bookworm\reader.py", line 77, in read_document
  File "bookworm\document_formats\pdf_document.py", line 82, in read
  File "bookworm\document_formats\pdf_document.py", line 77, in create_xpdf_document
  File "src/pyxpdf/document.pxi", line 114, in pyxpdf.xpdf.Document.__cinit__
  File "src/pyxpdf/document.pxi", line 216, in pyxpdf.xpdf.Document.check
pyxpdf.xpdf.PDFIOError: Failed to load D:\books\javascript\Черный Б. - Профессиональный TypeScript (Бестселлеры O'Reilly)- 2021.pdf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\menubar.py", line 199, in onOpenEBook
  File "bookworm\gui\book_viewer\__init__.py", line 342, in open_uri
  File "bookworm\gui\book_viewer\__init__.py", line 68, in __init__
  File "bookworm\gui\book_viewer\__init__.py", line 84, in init_resolver
  File "bookworm\gui\book_viewer\__init__.py", line 157, in resolve_document
  File "bookworm\gui\book_viewer\__init__.py", line 99, in resolve_document
  File "bookworm\reader.py", line 86, in read_document
bookworm.reader.ReaderError: Failed to open document

##i opend these files in adobe reader.
Adobe reader opens without problem
[Uploading web Браун И. - Веб-разработка с применением Node и Express (Бестселлеры O’Reilly) - 2021.pdf…]()
.

**Comment by Menelion** [comment]
Interesting. @shaxzodxasanov What happens if you rename the file to contain only English letters? Like, `typescript.pdf`? I'm asking because, as you probably know, I do speak Russian and I managed to open Russian-language books (FB2) in Bookworm.

**Comment by mush42** [comment]
Hi @shaxzodxasanov 

This issue is fixed in the latest alpha [v2022.1a1](https://github.com/blindpandas/bookworm/releases/tag/Bookworm-Release-(Build-v1.0.128)). Please reopen if you experience this issue in the new version.

Regards,

**Comment by shaxzodxasanov** [comment]
> Interesting. @shaxzodxasanov What happens if you rename the file to contain only English letters? Like, `typescript.pdf`? I'm asking because, as you probably know, I do speak Russian and I managed to open Russian-language books (FB2) in Bookworm.

Thank you. i don't know this method.
